// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/tundrawork/DG-citrus/biz/citrus-server"
	"github.com/tundrawork/DG-citrus/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/", citrus_server.RootHandler)
	r.GET("/ping", handler.Ping)

	v1 := r.Group("/v1")
	v1.GET("/ws", citrus_server.ThirdPartyWSHandler)
	v1.GET("/register", citrus_server.HTTPRegister)
	v1.GET("/bind", citrus_server.HTTPBindingQrcode)
	v1.GET("/command", citrus_server.HTTPCommand)
	v1.GET("/heartbeat", citrus_server.HTTPHeartbeat)
}
